name: laravel-tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports: ['3306:3306']
        options: >-
          --health-cmd="mysqladmin ping -ppassword --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, json, bcmath, fileinfo, pdo_mysql
          coverage: none

      - name: Copy .env
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Configure DB
        run: |
          php -r "file_put_contents('.env', preg_replace('/DB_CONNECTION=.*/','DB_CONNECTION=mysql', file_get_contents('.env')));"
          php -r "file_put_contents('.env', preg_replace('/DB_HOST=.*/','DB_HOST=127.0.0.1', file_get_contents('.env')));"
          php -r "file_put_contents('.env', preg_replace('/DB_PORT=.*/','DB_PORT=3306', file_get_contents('.env')));"
          php -r "file_put_contents('.env', preg_replace('/DB_DATABASE=.*/','DB_DATABASE=testing', file_get_contents('.env')));"
          php -r "file_put_contents('.env', preg_replace('/DB_USERNAME=.*/','DB_USERNAME=root', file_get_contents('.env')));"
          php -r "file_put_contents('.env', preg_replace('/DB_PASSWORD=.*/','DB_PASSWORD=password', file_get_contents('.env')));"

      - name: Migrate
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test --no-interaction
